version: '3'

services:
  github-concierge:
    build: .
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - .:/app/
    command: npm start
    env_file: .env

  storage:
    image: redis:3-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
  redis_data:
